### ISSUE TITLE
NG Input: Diagonal Mouse Movements

### ISSUE THREAD

**Issue by elstoc** [dterrahe/darktable#10]
With NG Input, it's possible to assign up/down and left/right to different shortcuts. However, in practical use, fine control of the sliders often requires very small mouse movements, for which it might be difficult to impossible to distinguish between up/down and left/right, and movements often impact both sliders at once. I know it's one less option but I'd prefer that the actions were just related to 'movements' rather than movements on independent axes. So up/right increases and down/left decreases.

Ref: darktable-org#8078

**Comment by elstoc** [comment]
Thinking about it you could do this more easily with up/down and left/right _scrolling_ - as far as I can see scrolls are either one or the other and not both.

**Comment by dterrahe** [comment]
The movements are intended to be discrete to some extend. The mouse should not respond to a very small move; if the stepsize is 0.1 moving the mouse just a little shouldn't give you 0.1 because then you'll could end up with any broken number which I don't think people want (moving the slider directly with the mouse also doesn't "scale down" the stepsize). So to get small moves, you can either still use the coarse/normal/fine settings you introduced or add a shortcut with a smaller speed settings (possibly via a fallback; any shortcut +ctrl will have their speed multiplied by .1 for example).

The different input methods (keyboard, mouse, midi, gamepad) need their own configuration options. If your mouse/touchpad is too sensitive, you'd want to be able to set a higher threshold value. Maybe even separately for horizontally/vertically. Mac people need different settings too, I believe. On the todo list...

**Comment by dterrahe** [comment]
> I know it's one less option but I'd prefer that the actions were just related to 'movements' rather than movements on independent axes.

One basic principle; nobody _has_ to use all the options. We don't need to take a feature away from everybody just because some/many/most people will decide not to use it.

_Unless_ of course it causes major inconvenience/confusion. And still, in that case a configuration option (in the mouse input dialog) that is _off_ by default would be better than just scrapping a feature.

I imagine the different axes will be used mainly for different speeds (via fallbacks). Scroll=normal speed, left/right=fine, up/down=coarse. But up to everybody to tailor to their preferences.

**Comment by dterrahe** [comment]
If this still needs fine-tuning, please refile with more detail in the main repo.
