### ISSUE TITLE
re-click on the shortcuts icons

### ISSUE THREAD

**Issue by AlicVB** [dterrahe/darktable#14]
I think it would be great if clicking again on the shortcut icon (the one in the global toolbox) deactivate the "point and click" feature. Otherwise it's not really clear how to quit that mode except by trying to click in a "blank" area, hoping that this won't define a new shortcut...
Especially as the "point and click" feature is not deactivated after the first shortcut definition (which is great)

**Comment by dterrahe** [comment]
Is this similar to #8? I'll definitely fix that! Since I myself just click anywhere to get out of shortcut mapping mode, I never really noticed. That's the kind of polishing that needs others to point out the things that don't affect me because I don't use them!

Also, everything is still very basic now; just all the features needed to make it work, but little extra polish. That will improve, trust me.

**Comment by AlicVB** [comment]
oops... sorry for the duplicate... it's not as if your issue list is difficult to search... shame on me !

and I trust you for the polishing, I just throw here little point I've seen in case you miss them ;)

**Comment by dterrahe** [comment]
Yeah!! Feels like a kind of graduation; receiving my first duplicate issue ;-)
