### ISSUE TITLE
FR: Searchable shortcut list

### ISSUE THREAD

**Issue by johnny-bit** [dterrahe/darktable#19]
**Is your feature request related to a problem? Please describe.**

But I cannot find any way to look for a particular shortcut. If I want to know what action is activated by the R shortcut, I expect at least that looking for "r" finds, with all the occurrencies of the r letter in the descriptions, the R shortcut too. But it doesn't happen.

**Describe the solution you'd like**

A searchbox for shortcuts
**Alternatives**

the help window with all shortcuts is hard to scan

**Additional context**

https://github.com/darktable-org/darktable/issues/6174

**Comment by dterrahe** [comment]
The "help" window and shortcut at the bottom of widget tooltips definitely need refinement. Not just to deal with the much larger number of possible shortcuts but also to be able to show fallbacks.

I think once the base framework has been merged, we can have more useful discussions around individual PRs just addressing this. Simply because more people will be using the framework and have ideas about it. That's why I haven't spent too much time polishing aspects that I would expect to be controversial or where the end result simply would benefit from a host of different viewpoints.

This also hasn't been a high priority for me because I find scanning an alphabetical list of shortcuts (once you ignore the modifiers) in either the shortcuts dialog or the help window not too difficult :-)

More seriously, the "solution" (_one_ of the solutions) I was thinking of is using the "online help" button (next to the shortcut button) to also handle help for unknown shortcuts; switch into help mode, press a (combined) shortcut -> get a popup with a full description of the action + element + effect + speed + instance (even if it is arrived at via fallbacks).

Other ideas very welcome, but as said, I will probably not implement before initial merge.

**Comment by johnny-bit** [comment]
I'm totally fine with that :)

The new input seems like magic - I've been testing it for last couple h and so far it hasn't broken on me and seems very powerful (and i'm not much of a key maniac)
