### ISSUE TITLE
NG Input: Key presses only increase sliders

### ISSUE THREAD

**Issue by elstoc** [dterrahe/darktable#5]
It is possible to (single/double-)press a key on a slider in the new input system. This key only ever _increases_ the slider value and I can't find a way to decrease it.

Ref: darktable-org#8078

**Comment by dterrahe** [comment]
"Effects" :-)
I wonder how many people sacrifice one scarce key for up and one key for down on a slider (since the introduction of dynamic sliders) but I'm definitely planning on supporting this.

Thanks for your thorough testing! Really much appreciated.

**Comment by elstoc** [comment]
Agreed but there only has to be one noisy user.

**Comment by dterrahe** [comment]
> Agreed but there only has to be one noisy user.

_One_ user we can ignore ;-)

No but more seriously, now that we've basically agreed to merge this post 3.6 I expect Effects (and possibly Fallbacks) to be in place by then.

**Comment by dterrahe** [comment]
Elements, effects and fallbacks have been implemented.

For single key press shortcuts linked to sliders, the user can change the effect the shortcut has by opening the shortcuts dialog (clicking on the slider while in "define shortcuts" mode opens the dialog with only shortcuts linked to that slider showing) and changing the setting in the "effect" column from the default "edit" (which opens the bauhaus edit popup, with the caveat mentioned in #17) to up or down (or reset/top/bottom).

The "element" can also be changed to "button", so that the shortcut toggles the quad area (normally color picker). If the user prefers "point&map", then hovering over the quad area while in "define shortcut" mode and pressing a key immediately maps that key to the "button" element.

But the intended way to use slider shortcuts, is to map one key (maybe double or triple pressed) to a slider and then to depend on the standard fallbacks to get the other functionality. Hold the key and:
- left click, for button (clickpicker)
- left double click for reset (hold after second click and move mouse up for max, down for min)
- ctrl for fine moves (1/10th; configurable by editing the speed for the value fallback)
- shift for coarse moves (10x)
- ctrl+shift for "forced" moves, that don't respect the soft min/max (and also 10x speed)

Please let me know if I've overlooked any existing functionality that cannot be replicated (yet) in this system by reopening this bug. Thanks!
