### ISSUE TITLE
NG Input: Not all buttons can be assigned

### ISSUE THREAD

**Issue by elstoc** [dterrahe/darktable#9]
There are a number of buttons that don't seem to be accessible to the NG Input system. Presumably they're part of phase 2?

For example, "darkroom/history/compress history stack", "darkroom/duplicate/duplicate", "darkroom/duplicate/original".

Hardly any of the widgets in the global color picker can be set, and none of the buttons in the histogram.

The multi-instance menu can't be set and neither can the enable/disable module button.

None of the bottom-panel buttons can be set.

Ref: darktable-org#8078

**Comment by dterrahe** [comment]
Correct. Those buttons are defined using different calls and aren't aware themselves which library/view they belong to. There needs to be some restructuring in bauhaus and in other dt widgets to properly support this and then this needs to be fixed in all the affected modules/views. That will cause the footprint of this PR to balloon (->continuous rebasing) so I've postponed all that work to later phases. Still not sure whether it should _all_ go into the first merge (it is not a _regression_) but hopefully by then (June) I'll have made progress on the infrastructure changes and then possibly the wider rollout across the ui codebase could follow quickly after, in separate self-contained PRs.

**Comment by dterrahe** [comment]
If there are still any buttons you think should have shortcuts please file FRs in the mean repo.
